### PR TITLE
Prep for prod

### PR DESCRIPTION
**Pull request by christophertull**

### CODE REVIEW

**Comment by patwater** [comment]
Are you looking for a code review or what needs to be done to merge this PR?

**Comment by christophertull** [comment]
Not sure if a code review is necessary. I guess only thing that might be nice is for someone to test out the new functionality on the live tool before I hit the "merge" button.

**Comment by patwater** [comment]
Do we have a list of test addresses? If not I can generate some and we can collab

**Comment by christophertull** [comment]
So far I have been using:

Work Correctly:
* Moulton Niguel Water District
* Los Angeles Cleantech Incubator
* Hilton San Francisco

Broken:
* City of Antioch

No data?:
* 446 Deodar Ave. Oxnard, CA

Feel free to expand

**Pull request merged**
